export const GREETING_PATTERNS = [
  /^(hi|hello|hey|greetings|good morning|good afternoon|good evening)[\s!.?]*$/i,
  /^(thanks|thank you|thx|ty|appreciate it)[\s!.?]*$/i,
  /^(bye|goodbye|see you|cya|take care)[\s!.?]*$/i,
  /^(how are you|what's up|sup|wassup|how's it going|how do you do)[\s!.?]*$/i,
  /^(سلام|درود|صبح بخیر|عصر بخیر|شب بخیر)[\s!.?]*$/i,
  /^(ممنون|متشکرم|مرسی|سپاس)[\s!.?]*$/i,
  /^(خداحافظ|بای|فعلاً)[\s!.?]*$/i,
  /^(حالت چطوره|چطوری|خوبی|چه خبر)[\s!.?]*$/i,
];

export const CRISIS_EXACT_KEYWORDS = [
  "suicide",
  "kill myself",
  "end my life",
  "self harm",
  "self-harm",
  "want to die",
  "hurt myself",
  "take my life",
  "خودکشی",
  "بمیرم",
  "خودم رو بکشم",
  "آسیب به خودم",
];

export const CRISIS_FUZZY_PATTERNS = [
  /su[ei]?[ck]?[ie]?[cd]e/i,
  /kill\s*(my\s*self|me)/i,
  /end\s*(my|this)\s*(life|pain)/i,
  /don'?t\s*want\s*to\s*(live|be here)/i,
  /want\s*to\s*(die|disappear)/i,
];

export const FILEISH_WORDS = [
  "page",
  "layout",
  "globals",
  "sidebar",
  "header",
  "footer",
  "login",
  "component",
  "screen",
  "view",
  "folder",
  "directory",
  "workspace",
  "codebase",
  "repo",
  "project",
  "app",
  "src",
  "routes",
  "uploads",
];

export const INSPECTION_ACCESS_WORDS = [
  "access",
  "have access",
  "do you have access",
  "can you access",
  "do you access",
  "read",
  "inspect",
  "check",
  "open",
  "show",
  "look at",
  "look into",
  "locate",
  "find",
  "see",
  "where is",
  "what files",
  "list files",
  "what file",
  "which file",
  "where should i",
  "what file do you want to update",
  "what file should i",
  "which file should i",
];

export const CODE_WORDS = [
  "give me code",
  "show code",
  "paste code",
  "full code",
  "content code",
  "send code",
  "whole code",
  "source code",
  "loginform content code",
  "component code",
  "file code",
  "give me the code",
  "show me the code",
  "full file",
  "full content",
];

export const ATTACHMENT_BUILD_WORDS = [
  "create",
  "build",
  "make",
  "implement",
  "design",
  "generate",
  "recreate",
  "clone",
  "copy",
  "match",
  "convert",
  "turn this into",
  "based on this",
  "based on these",
  "using this",
  "using these",
  "use this",
  "use these",
  "from this",
  "from these",
  "like this",
  "similar to this",
  "according to this",
  "this image",
  "this screenshot",
  "this file",
  "this design",
];

export const MODIFY_WORDS = [
  "change",
  "update",
  "modify",
  "edit",
  "refactor",
  "match",
  "sync",
  "align",
  "same style",
  "same colors",
  "same design",
  "redesign",
  "improve",
  "replace",
  "migrate",
  "fix",
  "adjust",
  "design",
  "style",
  "colors",
  "theme",
  "add signup",
  "add sign up",
  "sign up option",
  "signup option",
  "insert",
  "add",
  "implement",
  "create",
  "include",
  "append",
  "below the",
  "under the",
];

export const STRONG_MODIFY_WORDS = [
  "add",
  "implement",
  "create",
  "insert",
  "append",
  "include",
];

export const TECHNICAL_KEYWORDS = [
  "api",
  "backend",
  "frontend",
  "database",
  "auth",
  "dashboard",
  "react",
  "vue",
  "node",
  "fastify",
  "express",
  "postgresql",
  "mongodb",
  "microservice",
  "rest",
  "graphql",
  "websocket",
  "دیتابیس",
  "بک‌اند",
  "فرانت‌اند",
  "داشبورد",
  "احراز هویت",
  "page.tsx",
  "layout.tsx",
  "globals.css",
  "component",
  "file",
  "code",
  "design",
  "style",
  "match",
  "sync",
  "access",
  "inspect",
  "read",
  "login page",
  "sidebar",
  "chatbot",
  "folder",
  "directory",
  "workspace",
  "upload",
  "image",
  "screenshot",
  "file input",
  "attachment",
];

export const VAGUE_PATTERNS = [
  /create\s+(a\s+)?dashboard/i,
  /build\s+(a\s+)?website/i,
  /make\s+(an?\s+)?app/i,
  /develop\s+(a\s+)?system/i,
  /بساز\s+داشبورد/i,
  /بساز\s+وب‌سایت/i,
  /بساز\s+اپلیکیشن/i,
  /make\s+the\s+login\s+page/i,
  /match\s+the\s+design/i,
  /sync\s+the\s+design/i,
  /same\s+colors/i,
  /same\s+style/i,
];